# Generated by Django 5.0.3 on 2024-03-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id_imovel', models.BigAutoField(primary_key=True, serialize=False)),
                ('limite_hospedes', models.PositiveIntegerField()),
                ('quantidade_banheiros', models.IntegerField()),
                ('aceita_animal_estimacao', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_ativacao', models.DateField()),
                ('data_horario_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_horario_atualizacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.BigAutoField(primary_key=True, serialize=False)),
                ('plataforma_publicada', models.CharField(max_length=30)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_horario_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_horario_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('id_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comentario', models.TextField(default='', max_length=255, null=True)),
                ('numero_hospedes', models.PositiveIntegerField()),
                ('data_horario_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_horario_atualizacao', models.DateTimeField(null=True)),
                ('id_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anuncio')),
            ],
        ),
    ]
